name: Build Moodle App Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.17.0

    - name: Install dependencies
      run: |
        npm install
        npm install -g @ionic/cli cordova-res @capacitor/cli
        npm install @capacitor/android

    - name: Build Ionic App
      run: |
        ionic build
        npx cap init "TalkLine" "com.talkline.schoolapp" --web-dir=www
        npx cap sync
        npx cap add android

    - name: Update package name
      run: |
        sed -i 's/com.moodle.moodlemobile/com.talkline.schoolapp/g' android/app/src/main/AndroidManifest.xml
        sed -i 's/com.moodle.moodlemobile/com.talkline.schoolapp/g' android/app/build.gradle


    - name: Generate icons
      run: |
        cordova-res android --skip-config --copy

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: moodleapp-apk
        path: android/app/build/outputs/apk/release/app-release.apk
